using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace SweetCMS.DataAccess
{
    /// <summary>
    /// Controller class for TblTransactions
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TblTransactionController
    {
        // Preload our schema..
        TblTransaction thisSchemaLoad = new TblTransaction();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TblTransactionCollection FetchAll()
        {
            TblTransactionCollection coll = new TblTransactionCollection();
            Query qry = new Query(TblTransaction.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblTransactionCollection FetchByID(object Id)
        {
            TblTransactionCollection coll = new TblTransactionCollection().Where("Id", Id).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TblTransactionCollection FetchByQuery(Query qry)
        {
            TblTransactionCollection coll = new TblTransactionCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Id)
        {
            return (TblTransaction.Delete(Id) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Id)
        {
            return (TblTransaction.Destroy(Id) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Code,decimal Qty,decimal Rate,decimal Amount,string Type,string Status,DateTime DateX)
	    {
		    TblTransaction item = new TblTransaction();
		    
            item.Code = Code;
            
            item.Qty = Qty;
            
            item.Rate = Rate;
            
            item.Amount = Amount;
            
            item.Type = Type;
            
            item.Status = Status;
            
            item.DateX = DateX;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Id,string Code,decimal Qty,decimal Rate,decimal Amount,string Type,string Status,DateTime DateX)
	    {
		    TblTransaction item = new TblTransaction();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Code = Code;
				
			item.Qty = Qty;
				
			item.Rate = Rate;
				
			item.Amount = Amount;
				
			item.Type = Type;
				
			item.Status = Status;
				
			item.DateX = DateX;
				
	        item.Save(UserName);
	    }
    }
}
